commerce_payment.commerce_payment_gateway.plugin.coingate_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    coingate_api_auth_token:
      type: string
      label: 'API Auth Token'
    coingate_receive_currency:
      type: string
      label: 'Receive Currency'
